USE DB_MYRH
GO

-- 1. EXEMPLOS DE FUNÇÃO DE AGREGAÇÃO
SELECT
	SUM(SALARIO) AS SOMA,
	AVG(SALARIO) AS MEDIA,
	MAX(SALARIO) AS MAXIMO,
	MIN(SALARIO) AS MINIMO,
	STDEV(SALARIO) AS [DESVIO PADRAO],
	COUNT (SALARIO) AS QUANTIDADE
FROM TB_CARGOS

SELECT
	SUM (SALARIO) AS SOMA,
	COUNT (*) AS QUANT,
	TP_SALARIO
FROM
	TB_CARGOS
GROUP BY
	TP_SALARIO


-- Exercicio 01: apresentar a quantidade de inscrições por área
-- somente 2 colunas na resposta area e quantidade

SELECT
	A.DESCRICAO AS AREA,
	COUNT(*) AS [QTDE INSCRITOS]
FROM
	TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	A.DESCRICAO

-- exercicio 02: apresentar a quantidade de inscrições por cargo
-- somente 2 colunas na resposta: cargo e quantidade

SELECT
	C.DESCRICAO AS CARGO,
	COUNT(*) AS [QTDE INSCRITOS]
FROM
	TB_CARGOS C JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	--JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	--JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	C.DESCRICAO
