USE DB_MYTE
GO
 
CREATE TABLE TB_WBS(
	ID INT NOT NULL IDENTITY(1,1),
	CODIGO VARCHAR(10) NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	TIPO SMALLINT NOT NULL,
	PRIMARY KEY(ID),
	CHECK(TIPO = 1 OR TIPO = 2), --1: CHARGEABILITY, 2: NON-CHEARGEABILITY
	CHECK(CODIGO >= 4),
	UNIQUE(CODIGO)
);
GO
 
CREATE TABLE TB_AREA(
	ID INT NOT NULL IDENTITY(1,1),
	DESCRICAO VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
)
 
CREATE TABLE TB_CARGO(
	ID INT NOT NULL IDENTITY(1,1),
	DESCRICAO VARCHAR(50) NOT NULL,
	ID_AREA INT NOT NULL,
	SALARIO FLOAT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_AREA) REFERENCES TB_AREA(ID),
)
 
CREATE TABLE TB_COLABORADORES(
	ID INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(60) NOT NULL,
	ID_CARGO INT  NOT NULL,
	NM_MATRICULA INT NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CARGO) REFERENCES TB_CARGO(ID),
	UNIQUE(NM_MATRICULA)
)
 
CREATE TABLE TB_REGISTRO_HORAS(
	ID INT NOT NULL IDENTITY(1,1),
	QTD_HORAS FLOAT NOT NULL,
	DIA DATE NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_CARGO INT NOT NULL,
	ID_WBS INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID),
	FOREIGN KEY(ID_WBS) REFERENCES TB_WBS(ID),
)